const categories = {
  "Jobs": ["doctor", "teacher", "engineer", "chef", "firefighter", "pilot", "nurse", "lawyer", "mechanic", "artist"],
  "Food": ["pizza", "burger", "rice", "pasta", "salad", "sushi", "steak", "noodles", "tacos", "soup"],
  "House Objects": ["sofa", "lamp", "mirror", "bed", "chair", "table", "rug", "television", "bookshelf", "clock"],
  "Things in a Park": ["bench", "fountain", "slide", "tree", "swing", "duck", "path", "flower", "grass", "statue"],
  "Drinks": ["water", "coffee", "tea", "juice", "soda", "milk", "lemonade", "smoothie", "wine", "beer"],
  "Animals": ["dog", "cat", "elephant", "lion", "tiger", "giraffe", "bear", "zebra", "monkey", "rabbit"],
  "Numbers": ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"],
  "Filing Office Stuffs": ["folder", "stapler", "paperclip", "notepad", "binder", "pen", "pencil", "highlighter", "printer", "envelope"],
  "Bakery": ["bread", "croissant", "muffin", "donut", "bagel", "cake", "pie", "cupcake", "biscuit", "eclair"],
  "Vehicles": ["car", "bus", "bike", "train", "plane", "boat", "scooter", "truck", "subway", "helicopter"],
  "Fruits": ["apple", "banana", "orange", "grape", "pineapple", "mango", "peach", "strawberry", "kiwi", "watermelon"],
  "Supermarket Areas": ["produce", "dairy", "bakery", "frozen", "meat", "seafood", "beverages", "cleaning", "snacks", "checkout"],
  "Things in a Pool": ["goggles", "float", "kickboard", "water", "swimsuit", "towel", "pool noodle", "lifeguard", "diving board", "chlorine"],
  "Plants": ["rose", "tulip", "fern", "cactus", "bamboo", "orchid", "ivy", "daisy", "sunflower", "lily"],
  "Birds": ["sparrow", "eagle", "parrot", "pigeon", "owl", "peacock", "duck", "swan", "crow", "flamingo"],
  "Church": ["altar", "pew", "priest", "cross", "choir", "bible", "candles", "organ", "window", "prayer"],
  "Car Stuffs": ["tire", "engine", "steering wheel", "seatbelt", "brake", "mirror", "headlight", "bumper", "windshield", "dashboard"],
  "Sports": ["soccer", "basketball", "tennis", "baseball", "volleyball", "swimming", "cycling", "golf", "boxing", "hockey"],
  "Football Stuffs": ["ball", "goal", "referee", "whistle", "cleats", "jersey", "net", "stadium", "corner flag", "substitute"],
  "Basketball Stuffs": ["basketball", "hoop", "court", "backboard", "net", "jersey", "referee", "dribble", "three-pointer", "rebound"],
  "Pub": ["beer", "barstool", "dartboard", "jukebox", "pint", "menu", "bartender", "coaster", "snacks", "glass"],
  "Restaurant": ["menu", "waiter", "table", "plate", "fork", "glass", "chef", "napkin", "bill", "reservation"],
  "Hospital": ["doctor", "nurse", "bed", "stethoscope", "ambulance", "patient", "syringe", "mask", "x-ray", "wheelchair"],
  "Shopping Center": ["store", "mall", "escalator", "food court", "restroom", "clothes", "cashier", "window display", "bag", "parking"],
  "Beach": ["sand", "sea", "shell", "towel", "umbrella", "sunscreen", "waves", "surfboard", "beach ball", "cooler"],
  "Sky": ["cloud", "sun", "moon", "stars", "plane", "rainbow", "bird", "helicopter", "kite", "balloon"]
};
